services:
  # 容器名称
  jenkins:
    container_name: jenkins
    # 构建所使用的镜像
    image: tomcat:7-jre8
    ports:
      - 8080:8080
    # 映射容器内数据目录挂载到宿主机的目录
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # 确保宿主机目录里有war包
      - /opt/project/webapps:/usr/local/tomcat/webapps
    # 容器随docker自动启动
    restart: always
    # privileged: true
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://github.com/niushuai1991
