services:
  # 容器名称
  vaultwarden:
    container_name: vaultwarden
    # 构建所使用的镜像
    image: vaultwarden/server:1.33.2
    # ports:
      # - 13928:80
      # - 3012:3012
    volumes:
      - vaultwarden_volume:/data
    # 容器随docker自动启动
    restart: always
    networks:
      - mynet
    environment:
      - TZ=Asia/Shanghai
      - SIGNUPS_ALLOWED=false
      - WEBSOCKET_ENABLED=false
volumes:
  vaultwarden_volume:
networks:
  mynet:
    external: true