networks:
  es-net:
    external: false
services:
  # 容器名称
  elasticsearch:
    container_name: elasticsearch
    # 构建所使用的镜像
    image: elasticsearch:7.17.24
    ports:
    # 宿主机端口:容器端口
      - 9200:9200
      - 9300:9300
    # 映射容器内/data目录到宿主机的目录
    volumes:
      - /opt/server/drone/data:/data
    # 容器随docker自动启动
    restart: always
    networks:
      - es-net
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: kibana:7.17.24
    restart: always
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
    # 宿主机端口:容器端口
      - 5601:5601
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
