services:
  # 容器名称
  jenkins:
    container_name: jenkins
    # 如果需要DinD就要使用root
    user: root
    # 构建所使用的镜像
    image: jenkins/jenkins:lts
    ports:
      - 8000:8080
      - 50000:50000
    # 映射容器内数据目录挂载到宿主机的目录
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jenkins_home:/var/jenkins_home
      # DinD必要的几个参数
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    # 容器随docker自动启动
    restart: always
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://github.com/niushuai1991
volumes:
  jenkins_home:
networks:
  mynet:
    external: true
